
// Generated by https://quicktype.io

export interface EpisodeWithImage {
    id:     number;
    name:   string;
    slug:   string;
    season: Season;
}

export interface Season {
    image_url: string;
}
