// Generated by https://quicktype.io

export interface Episode {
    id:       number;
    name:     string;
    number:   number;
    duration: string;
    url:      string;
    slug:     string;
    season:   Season;
}

export interface Season {
    slug: string;
}
